Refactor "clean old client keys"
ORCID/ORCID-Source pull request #6293
Opened 2021-08-09 14:05 UTC by auumgn

2021-08-10 13:56 UTC, amontenegro requested changes

2021-08-10 13:56 UTC, amontenegro commented on orcid-core/src/main/java/org/orcid/core/cron/CleanOldClientKeysCronJob.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(ClientDetailsManagerImpl.class);
@auumgn please use CleanOldClientKeysCronJob.class instead in the logger

2021-08-10 13:56 UTC, amontenegro commented on orcid-persistence/src/main/java/org/orcid/persistence/dao/impl/ClientSecretDaoImpl.java
> +        TypedQuery<ClientSecretEntity> query = entityManager.createQuery("From ClientSecretEntity WHERE is_primary = true and last_modified + '24 hours' > '2021-01-01'", ClientSecretEntity.class);
@auumgn `is_primary = true` use `false`

2021-08-10 13:56 UTC, amontenegro commented on orcid-core/src/main/java/org/orcid/core/cron/CleanOldClientKeysCronJob.java
> +                String s = String.format("client_details_id = '%1$s' and client_secret = '%2$s'", clientId, key);
@auumgn please surround each entry in parentheses

2021-08-10 13:56 UTC, amontenegro commented on orcid-core/src/main/java/org/orcid/core/cron/CleanOldClientKeysCronJob.java
> +            LOGGER.info("The following keys are going to be deleted:\n" + queryConditionString.replace(" =", ":").replace(" and", ",").replace(" or", "\n").replace("'",""));
Make this LOGGER.info a LOGGER.warn

2021-08-10 15:08 UTC, auumgn commented
![](https://github.trello.services/images/mini-trello-icon.png) [Optimize the cleanOldClientKeys Spring cron job](https://trello.com/c/uxD5ItKd/7470-optimize-the-cleanoldclientkeys-spring-cron-job)

2021-08-13 14:22 UTC, amontenegro requested changes

2021-08-13 14:22 UTC, amontenegro commented on orcid-core/src/test/java/org/orcid/core/cron/CleanOldClientKeysCronJobTest.java
> +        Mockito.verify(clientSecretDao, Mockito.times(1)).removeWithCustomCondition(condition.capture());
@auumgn lets get the content of that parameter and assert that it contains what you expects.

2021-08-13 14:22 UTC, amontenegro commented on orcid-core/src/test/java/org/orcid/core/cron/CleanOldClientKeysCronJobTest.java
> +        Mockito.verify(clientDetailsDao, Mockito.times(1)).updateLastModifiedBulk(Mockito.anyList());
Evaluate what you capture.

2021-08-13 14:22 UTC, amontenegro commented on orcid-core/src/test/java/org/orcid/core/cron/CleanOldClientKeysCronJobTest.java
> +        Mockito.verify(clientDetailsDao, Mockito.times(1)).updateLastModifiedBulk(Mockito.anyList());
Evaluate what you capture.

2021-08-18 20:29 UTC, amontenegro requested changes

2021-08-18 20:29 UTC, amontenegro commented on orcid-persistence/src/main/java/org/orcid/persistence/dao/impl/ClientSecretDaoImpl.java
> +        DateTime dt = DateTime.now();
Hey @auumgn, you are not updating this dt, so, it keeps being now(), please update it so it is now() - 24 hours before assign it to the "yesterday" variable.

Thanks

2021-11-18 17:53 UTC, amontenegro approved these changes

2021-11-18 17:53 UTC, merged