Remove togglz and associated code for VERBOSE_NOTIFICATIONS
ORCID/ORCID-Source pull request #6311
Opened 2021-08-20 11:30 UTC by auumgn

2021-08-20 14:02 UTC, auumgn commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove togglz VERBOSE_NOTIFICATIONS](https://trello.com/c/DEhWnU0F/7509-remove-togglz-verbosenotifications)

2021-08-24 01:14 UTC, amontenegro requested changes

2021-08-24 01:14 UTC, amontenegro commented on orcid-core/src/main/java/org/orcid/core/manager/impl/EmailMessageSenderImpl.java
> -                        digestMessage = createDigestLegacy(orcid, notifications);
@auumgn looks like you can also delete the function `createDigestLegacy` since no one use it anymore.

2021-08-24 21:40 UTC, amontenegro requested changes

2021-08-24 21:40 UTC, amontenegro commented on orcid-web/src/main/resources/freemarker/includes/ng2_templates/notification-body-ng2-template.ftl
> -                <div *ngIf="TOGGLZ_VERBOSE_NOTIFICATIONS; else defaultNotifications">
Hey @auumgn look at this .... `else defaultNotifications` means that the `ng-template`  defaultNotifications will be displayed if the ngIf condition is false; so, please go ahead and remove this ng-template as well:


https://github.com/ORCID/ORCID-Source/pull/6311/files#diff-77a64175978df96cacd724d668cc06db330a99231ec3786e5d662952cef49ccbR122

2021-09-02 19:38 UTC, merged