Feature/add locked reason to lookup tool
ORCID/ORCID-Source pull request #6352
Opened 2021-10-08 11:42 UTC by auumgn

2021-10-13 16:38 UTC, auumgn commented
![](https://github.trello.services/images/mini-trello-icon.png) ["Lock record" admin function: make Description mandatory, store date of the record was locked and iD of Admin](https://trello.com/c/SnK2kthr/7575-lock-record-admin-function-make-description-mandatory-store-date-of-the-record-was-locked-and-id-of-admin)

2021-11-18 19:21 UTC, amontenegro requested changes

2021-11-18 19:21 UTC, amontenegro commented on orcid-persistence/src/main/java/org/orcid/persistence/dao/impl/ProfileDaoImpl.java
> +        String reason = " for: " + (String) result.get(0)[0];
@auumgn lets do this in the manager or controller side of things, not in the DAO

2021-11-22 20:48 UTC, amontenegro requested changes

2021-11-22 20:48 UTC, amontenegro commented on orcid-persistence/src/main/resources/db-master.xml
> +	<include file="/db/updates/add_column_record_locked_admin_id.xml" />
@auumgn just to be a really pain ... could you please keep just 1 file for this? You just need to merge the two files by keeping both `<changeSet>` , and then please format the code.

Thanks

2022-01-18 18:52 UTC, amontenegro approved these changes

2022-01-18 18:52 UTC, merged