Feature/update pmid prefix
ORCID/ORCID-Source pull request #6405
Opened 2021-12-27 14:58 UTC by auumgn

2021-12-27 17:02 UTC, auumgn commented
![](https://github.trello.services/images/mini-trello-icon.png) [PubMed ID resolution prefix](https://trello.com/c/ihObl4nm/7859-pubmed-id-resolution-prefix)

2022-01-06 20:33 UTC, amontenegro requested changes

2022-01-06 20:33 UTC, amontenegro commented on orcid-persistence/src/main/resources/db/updates/identifier-types/add-primary-use-and-urls.xml
> +		<sql>UPDATE identifier_type SET id_resolution_prefix = 'http://pubmed.ncbi.nlm.nih.gov/' WHERE id_name = 'PMID';</sql>
@auumgn this is wrong.

2022-01-06 20:33 UTC, amontenegro commented on orcid-persistence/src/main/resources/db/updates/identifier-types/update-to-https.xml
> +			UPDATE identifier_type SET id_resolution_prefix = 'https://pubmed.ncbi.nlm.nih.gov/' WHERE id_name = 'PMID';
@auumgn this is wrong.

2022-01-06 20:34 UTC, amontenegro commented
@auumgn you should create a new liquibase change set (new xml) for doing this.

Please rollback the changes you did in the existing xml files and create a new one.

Thanks

2022-01-18 18:02 UTC, amontenegro requested changes
@auumgn you will need to add update-pmid-resolution-prefix.xml  to the db-master.xml file, so, liquibase is aware of it.

2022-01-19 19:53 UTC, merged