Allow obo revoked tokens
ORCID/ORCID-Source pull request #6579
Opened 2022-06-21 16:57 UTC by amontenegro

2022-06-22 12:42 UTC, Camelia-Orcid commented
![](https://github.trello.services/images/mini-trello-icon.png) [[R&D] - Investigate steps needs to implement ML approach to spam](https://trello.com/c/jmowcz6n/8154-rd-investigate-steps-needs-to-implement-ml-approach-to-spam)

2022-06-23 21:29 UTC, amontenegro commented
![](https://github.trello.services/images/mini-trello-icon.png) [OBO token exchange fails for revoked tokens](https://trello.com/c/Mct3mJMg/8176-obo-token-exchange-fails-for-revoked-tokens)

2022-06-23 21:32 UTC, DanielPalafox requested changes

2022-06-23 21:49 UTC, DanielPalafox approved these changes

2022-06-23 22:01 UTC, merged