Removed profile from cache for all reset password and reset the locked fields
ORCID/ORCID-Source pull request #6585
Opened 2022-06-29 14:51 UTC by Camelia-Orcid

2022-06-29 14:52 UTC, Camelia-Orcid commented
![](https://github.trello.services/images/mini-trello-icon.png) [[QA] Unable to sign in after password reset for account in lockout](https://trello.com/c/rEtxXgdS/38-qa-unable-to-sign-in-after-password-reset-for-account-in-lockout)

2022-06-30 19:22 UTC, amontenegro requested changes

2022-06-30 19:22 UTC, amontenegro commented on orcid-web/src/main/java/org/orcid/frontend/web/controllers/PasswordResetController.java
> -        if (Features.ENABLE_ACCOUNT_LOCKOUT.isActive()) {
@Camelia-Orcid why did you remove the togglz from here?

2022-07-04 16:27 UTC, amontenegro approved these changes

2022-07-04 16:27 UTC, merged