7990 qa admin function record locked date is displayed as current date
ORCID/ORCID-Source pull request #6596
Opened 2022-07-06 23:58 UTC by DanielPalafox

2022-07-06 23:58 UTC, DanielPalafox commented
![](https://github.trello.services/images/mini-trello-icon.png) [[QA] Admin function, record locked date is displayed as current date](https://trello.com/c/WbjxlvhZ/7990-qa-admin-function-record-locked-date-is-displayed-as-current-date)

2022-07-07 14:34 UTC, amontenegro requested changes

2022-07-07 14:34 UTC, amontenegro commented on orcid-core/src/main/java/org/orcid/core/manager/v3/read_only/impl/ProfileEntityManagerReadOnlyImpl.java
> +        } else if (profileEntity.getLastIndexedDate() != null) {
@DanielPalafox this should be getLastModifiedDate() instead of getLastIndexedDate() right?

2022-07-07 16:57 UTC, amontenegro approved these changes

2022-07-07 16:57 UTC, merged