First draft education, qualifications, research resources, email domains added to record summary
ORCID/ORCID-Source pull request #7084
Opened 2024-09-12 08:01 UTC by Camelia-Orcid

2024-09-16 16:14 UTC, amontenegro requested changes

2024-09-16 16:14 UTC, amontenegro commented on orcid-core/src/main/java/org/orcid/core/model/EducationQualification.java
> +@XmlRootElement(name = "education-qualification", namespace = "http://www.orcid.org/ns/summary")
@Camelia-Orcid lets split this into multiple files, one per activity type

2024-09-16 16:26 UTC, amontenegro commented
@Camelia-Orcid we need to update the XSD, so, please send a PR on the orcid model and update the version here, thanks!

2024-09-16 19:06 UTC, Camelia-Orcid commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add Education and qualifications, email domain and Research Resources to the /summary endpoint and /summary.json](https://trello.com/c/6Xr52439/9393-add-education-and-qualifications-email-domain-and-research-resources-to-the-summary-endpoint-and-summaryjson)

2024-09-17 15:14 UTC, amontenegro approved these changes

2024-09-17 15:14 UTC, merged