Api limiting http request filter
ORCID/ORCID-Source pull request #7110
Opened 2024-10-25 13:37 UTC by Camelia-Orcid

2024-10-28 14:31 UTC, Camelia-Orcid commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add additional API Usage data to panoply](https://trello.com/c/ysV8jKwE/9451-add-additional-api-usage-data-to-panoply)

2024-10-29 17:04 UTC, amontenegro requested changes

2024-10-29 17:04 UTC, amontenegro commented on orcid-pub-web/src/main/resources/orcid-t1-web-context.xml
> +
Please remove these extra lines

2024-10-29 17:04 UTC, amontenegro commented on orcid-pub-web/src/main/java/org/orcid/api/filters/ApiRateLimitFilter.java
> +        LOG.info("ApiRateLimitFilter starts, rate limit is : " + enableRateLimiting);
@Camelia-Orcid could you please make this one a `trace` instead of `info`? 
Thanks

2024-10-30 13:51 UTC, merged