Fixes for the ML startup error
ORCID/ORCID-Source pull request #7114
Opened 2024-10-28 19:53 UTC by Camelia-Orcid

2024-10-28 19:53 UTC, Camelia-Orcid commented
![](https://github.trello.services/images/mini-trello-icon.png) [[PROD] Unable to start ML](https://trello.com/c/rOUGuaVS/9456-prod-unable-to-start-ml)

2024-10-28 21:14 UTC, amontenegro requested changes

2024-10-28 21:14 UTC, amontenegro commented on orcid-activemq/src/main/resources/message-listener.properties
> +org.orcid.persistence.panoply.cleanup.production=false
@Camelia-Orcid do we need this one here? org.orcid.persistence.panoply.cleanup.production=false

2024-10-29 15:12 UTC, amontenegro approved these changes

2024-10-29 15:29 UTC, merged